### ISSUE TITLE
v1.8.2

### ISSUE THREAD

**Issue by ikemo3** [ikemo3/gossip-site-blocker#12]
# ToDo

* [x] 開発完了
* [x] CHANGELOG.mdの更新
* [x] Chromeで確認
    * [x] **「禁止用語でブロックされたサイトの情報を表示(β)」がonのときの動作**
    * [x] **「禁止用語でブロックされたサイトの情報を表示(β)」がoffのときの動作**
    * [x] 基本のブロック機能
    * [x] トップニュース(カード型)のブロック機能(キーワード: 「野球」)
    * [x] 動画のブロック機能
    * [x] **Tweet(カード型)のブロック機能**
* [x] Firefoxで確認
    * [x] **「禁止用語でブロックされたサイトの情報を表示(β)」がonのときの動作**
    * [x] **「禁止用語でブロックされたサイトの情報を表示(β)」がoffのときの動作**
    * [x] 基本のブロック機能
    * [x] トップニュース(カード型)のブロック機能(キーワード: 「野球」)
    * [x] 動画のブロック機能
    * [x] **Tweet(カード型)のブロック機能**
* [x] リリース準備
    * [x] manifest.jsonのバージョンを変更
    * [x] タグの作成
    * [x] 署名付きアーカイブ(.crx)の作成
* [x] Chrome Web Storeにリリース
* [x] Firefox Add-onsにリリース
* [x] ブログを記載
