### ISSUE TITLE
Block articles in the News tab of search results individually / 検索結果の「ニュース」タブの記事を個別にブロックする

### ISSUE THREAD

**Issue by ikemo3** [ikemo3/gossip-site-blocker#14]
現在Google検索の「ニュース」タブをクリックしたときに同じ内容に対して複数の記事がある場合、以下の問題がある。

* 先頭の記事がブロック対象になっているため、他の記事は開かないと読めない
* 他の記事はブロック対象になっていない

特に後者が致命的なので修正する必要がある。

## 調査結果

* 先頭の記事がブロック対象になっているのは `class="g"` のため
    * `class="top"` で画像、それ以外は `class="gG0TJc"` で取れるようだ。
    * 画像をブロックするかどうかの考慮が必要
    * 個別に表示を制御するか、2つを `<div>` で囲むかのどちらか。後者でも崩れは発生しなさそう。
* それ以外は `class="card-section"` で区別するので良さそう。
    * こちらの方だけ優先するのもアリか。
* レイアウト調整
    * 画像には3つのclassがついている。
        * `class="dfhHve"` に画像のサイズ `width: 100px`
        * `class="NQHJEb"` に `margin-right: 8px`

## ToDo

* [x] 既存のコードの整理
    * ブロックのパターン間で重複しているコードを何とかしたい
* [x] パターン対応
    * [x] card-section
    * [x] top
* [x] レイアウト調整
    * [x] 一番最後の記事のブロックリンクの位置がずれている
    * [x] コンパクトモード時のメニューの位置の調整
        * [x] `class="top"`: 下に移動
        * [x] `class="card-section"`: 3px右にずらす
    * [x] 「すべて表示」がブロックされないようにする
    * [x] ハードブロックの場合、画像からリンクを外す
* [x] オプション機能の追加
* [x] その他
    * [x] GoogleTopNewsとGoogleNewsTopという似た名前のクラスがあるので整理する。
        * 前者が検索結果の「トップニュース」、後者がGoogleニュースでグループ化された場合の最初の記事

## テスト

* [x] ブロックのテスト(デフォルト)
    * [x] Google Newsで画像があるもの(class="top"がある)
    * [x] Google Newsでグループ化されているもの(class="card-section"がある)
    * [x] 「すべて表示」が出る場合
* [x] ブロックのテスト(コンパクト)
    * [x] Google Newsで画像があるもの(class="top"がある)
    * [x] Google Newsでグループ化されているもの(class="card-section"がある)
    * [x] 「すべて表示」が出る場合
* [x] メニューの位置のテスト
    * [x] デフォルト
    * [x] コンパクトモード

**Comment by ikemo3** [comment]
Reopen this because there are tasks.
