### ISSUE TITLE
v1.11.0

### ISSUE THREAD

**Issue by ikemo3** [ikemo3/gossip-site-blocker#179]
## ToDo

* [x] 開発完了
* [x] 新機能の動作確認
    * [x] Chrome
        * [x] 画像タブのブロック(Selenium)
            * [x] ソフトブロック
            * [x] ハードブロック
        * [x] 【「画像」タブをブロック】オプションをオフ(Selenium)
    * [x] Firefox
        * [x] 画像タブのブロック(Selenium)
            * [x] ソフトブロック
            * [x] ハードブロック
        * [x] 【「画像」タブをブロック】オプションをオフ(Selenium)
* [x] Seleniumで確認(`yarn integration-test`)
    * [x] スクリーンショットを一通り確認
* [x] Chromeで確認
    * [x] 戻るボタンを押したときにブロックされること
        * [x] 一部ゴミが表示されるが軽微(#146)
* [x] Firefoxで確認
    * [x] 戻るボタンを押したときにブロックされること
* [x] エラーが出てないことの確認
* [x] リリース準備
    * [x] CHANGELOG.mdの更新
    * [x] manifest.jsonのバージョンを変更
    * [x] package.jsonのバージョンを変更
    * [x] manifest.jsonから `version_name` を削除
* [x] タグの作成
* [x] リリースバージョンをダウンロード
    * [x] 簡単な動作確認
* [x] Chrome Web Storeにリリース
* [x] Firefox Add-onsにリリース
* [x] ブログを更新
    * [x] 記事を追加
    * [x] 更新履歴を追加(英語)
    * [x] 更新履歴を追加(日本語)
* [x] バージョンを変更
    * [x] `apps/manifest.json`: version, version_nameを更新
    * [x] `package.json`: versionを更新
* [x] リリーステンプレートに反映させる
* [x] 次の次のバージョンのマイルストーンを作成
* [x] マイルストーンをクローズ
