### ISSUE TITLE
v1.12.2

### ISSUE THREAD

**Issue by ikemo3** [ikemo3/gossip-site-blocker#296]
## ToDo

* [x] 開発完了
* [x] リリース準備
    * [x] CHANGELOG.mdの更新
    * [x] manifest.jsonのバージョンを変更
    * [x] package.jsonのバージョンを変更
    * [x] manifest.jsonから `version_name` を削除
* [x] タグの作成
* [x] リリースバージョンをダウンロード
    * [x] 簡単な動作確認
* [x] Chrome Web Storeにリリース
* [x] Firefox Add-onsにリリース
* [x] バージョンを変更
    * [x] `apps/manifest.json`: version, version_nameを更新
    * [x] `package.json`: versionを更新
* [x] リリーステンプレートに反映させる
* [x] 次の次のバージョンのマイルストーンを作成
* [x] マイルストーンをクローズ
