### ISSUE TITLE
v1.8.4.1(Firefox only)

### ISSUE THREAD

**Issue by ikemo3** [ikemo3/gossip-site-blocker#94]
## ToDo

* [x] 開発完了
* [x] CHANGELOG.mdの更新
* [x] Firefoxで確認
    * [x] 基本のブロック機能
    * [x] トップニュース(カード型)のブロック機能
    * [x] 動画のブロック機能・・・修正済み(#88)
    * [x] Tweet(カード型)のブロック機能
    * [x] コンパクトモード時のアイコンの位置
        * [x] 基本
        * [x] トップニュース・・・クリックできないが今回はリリース優先(#41)
        * [x] 動画
        * [x] Tweet(カード型)
* [x] スクリーンショットがおかしくないことの確認
* [x] リリース準備
    * [x] manifest.jsonのバージョンを変更
    * [x] package.jsonのバージョンを変更
    * [x] manifest.jsonから `version_name` を削除
    * [x] タグの作成
* [x] Firefox Add-onsにリリース
* [x] ブログを更新
    * [x] 記事を追加
    * [x] 更新履歴を追加(英語)
    * [x] 更新履歴を追加(日本語)
* [x] リリーステンプレートに反映させる
* [x] バージョンを変更
    * [x] `apps/manifest.json`: version, version_nameを更新
    * [x] `package.json`: versionを更新
